# Generated by Django 5.1 on 2024-08-12 03:36

import DocSummarizerApp.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSummarizerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=DocSummarizerApp.storages.OutsideRootStorage(), upload_to='UploadedDocuments'),
        ),
    ]
