# Generated by Django 5.1.1 on 2024-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocSummarizerApp', '0002_remove_document_uploaded_at_document_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
