# Generated by Django 5.1.1 on 2024-09-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocSummarizerApp', '0003_document_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='summary',
        ),
    ]
